### PR TITLE
Add template

### PR DESCRIPTION
**Pull request by sayedihashimi**
I've made some changes to make this into a project.

I renamed the project to include a common name (`MyCloudService`) and to also include a `.`. Having a `.` is important for getting the replacements correct.

Some things you likley want to update before shipping:
 - Fill in NuGet metadata in file at `CloudService.TemplatePack/template/templatepack.CloudService.TemplatePack.proj`
 - Fill in VS Extension metadata at `CloudService.TemplatePack/source.extension.vsixmanifest`

I noticed after project create that the initial build fails, but further builds work. This is the same experience I had when I clone this repo for the first time. Not sure what's causing that.

When you are ready you should publish the following:
 - nuget package to nuget.org
 - .vsix file to the VS marketplace

If you have questions let me know

### CODE REVIEW

**Comment by clairernovotny** [comment]
@sayedihashimi Thank you for this!

The clean build scenario should be fixed now; I added a build dependency between the WebRole and the Website to ensure they're not built in parallel...I think that was the issue.

Couple of questions since I'm not overly familiar with creating templates:

1. What should the NuGet be named? Right now it's creating it with packageId `templatepack.CloudService.TemplatePack`
2. What's the best way to test this? 
3. How do the VSIX and NuGet package relate?
4. Is there an easy way to specify the output path of the NuGet and VSIX (suppose I wanted it in an ..\artifacts directory)?

**Comment by sayedihashimi** [comment]
> What should the NuGet be named? Right now it's creating it with packageId templatepack.CloudService.TemplatePack

The name is derived from the `PackageId` property and if that is not set the file name is used. In your case I think it's better to add a new property `PackageId`. The name of the file must be in the format `template.*.proj`

FYI see NuGet csproj ref at https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties for more properties you may want to se.

>   What's the best way to test this?

Initially you can start with `dotnet new --install <path-to-root-folder>`. After you get that working you should uninstall it with `dotnet new --install <full-path-to-root-folder>`. Run a build and then do `dotnet new --install <nuget-pkg-path>` to test the template coming out of the .nupkg file.

> How do the VSIX and NuGet package relate?
The .nupkg contains the template content. The .nupkg is embedded in the .vsix. When you release you should do the following:
 - Update version number in .nupkg
 - Update version number of vsix 
 - Publish .nupkg to nuget.org (or whatever nuget repo you are going to)
 - Publish .vsix to VS marketplace (or wherever you are sharing that file)

> Is there an easy way to specify the output path of the NuGet and VSIX (suppose I wanted it in an ..\artifacts directory)?

These files are going into the output folder. If you want them somewhere else I'd recommend you copy the file to the final location after the build has completed with a custom target. If that doesn't work for you let me know why.

**Comment by sayedihashimi** [comment]
BTW you should take a look at the `Content` folder in the .nupkg. If extra files are being included in the content you can exclude them by updating the template.*.proj file by adding additional `ExcludeFromPackage ` elements. If you have questions let me know.

**Comment by sayedihashimi** [comment]
Hi @onovotny any questions on this? I just wanted to double check that you have everything that you need here.

**Comment by clairernovotny** [comment]
Thanks, I think so, just haven't had time to test.

**Comment by clairernovotny** [comment]
Thanks!

**Comment by clairernovotny** [comment]
@sayedihashimi I added some auto versioning so the nuget and vsixmanifest get auto-incremented automatically and stay in sync.

This appears to all work, but I'd appreciate if you can give the final artifacts a glance and confirm?
https://ci.appveyor.com/project/onovotny/aspnetcorecloudservice/build/1.0.9/artifacts

**Pull request merged**
